### ISSUE TITLE
Get Interval precision from system table in Exasol SQL dialect

### ISSUE THREAD

**Issue by redcatbear** [exasol/virtual-schemas#133]
# Situation
Currently the precision of `INTERVAL` data types is hard-coded in the Exasol SQL dialect. The necessary information is not available via JDBC.

# Acceptance Criteria
* Ask the JDBC driver developers if it is possible to provide that precision via JDBC.
* If yes: ticket for JDBC driver is created
* If no: obtain precision from system tables

**Comment by jakobbraun** [comment]
moved to https://github.com/exasol/exasol-virtual-schema/issues/16
