### ISSUE TITLE
Finish implementation of MySQL dialect 

### ISSUE THREAD

**Issue by AnastasiiaSergienko** [exasol/virtual-schemas#140]
### Problem
1) Finish implementation of this dialect and add as a supported dialect
2) Add ANSI_QUOTES option into public String applyQuote(final String identifier)  method. Must be obtained from JDBC DatabaseMetadata.
 http://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_ansi_quotes

### Where? 
MysqlSqlDialect class

**Comment by redcatbear** [comment]
Removed the MySQL dialect completely.
