### ISSUE TITLE
[04000] More than one identity column returned by adapter for table ALL_DATATYPES 

### ISSUE THREAD

**Issue by ThomasBestfleisch** [exasol/virtual-schemas#15]
In some databases like postgresql it's possible to have more than one identity/autoincrement column per table.
As this is not allowed in EXASOL the exception
> [04000]  More than one identity column returned by adapter for table

is thrown.

To solve this rare situation, it would be great to have a global property like **IGNORE_AUTOINCREMENT_CONSTRAINTS=true** in the adapter definition.

**Comment by redcatbear** [comment]
Closing in accordance with PM.
