### ISSUE TITLE
Integration Tests: Automatically Close Resultsets

### ISSUE THREAD

**Issue by andrehacker** [exasol/virtual-schemas#17]
**Background:**
Currently, the integration test framework allows to run queries on virtual tables using [executeQuery()](https://github.com/EXASOL/virtual-schemas/blob/master/jdbc-adapter/virtualschema-jdbc-adapter/src/test/java/com/exasol/adapter/dialects/AbstractIntegrationTest.java#L58), however, the returned ResultSets are never closed. Having too many ResultSets probably causes problems at some point (they already caused problems with the Teradata jdbc driver, when the JdbcMetadataReader did not close his ResultSets, which is now fixed).

**Proposed Improvement:**
The AbstractIntegrationTest framework should somehow remember the returned ResultSets and close them all automatically at some kind of tearDown method at the end of a test. Or we should find any other way to make sure that resultsets are closed as quickly as possible automatically.

**Comment by redcatbear** [comment]
Deriving unit tests is not the best possible way. I would suggest to port the unit tests to JUnit5 (#67) and use  extensions hooked into the test life cycle to clean up.

**Comment by redcatbear** [comment]
Old test framework has been replaced by testcontainers.
