### ISSUE TITLE
Support for native import from Oracle

### ISSUE THREAD

**Issue by hendrikcech** [EXASOL/virtual-schemas#26]
**Background**:
Virtual schemas for Oracle data sources currently uses IMPORT FROM JDBC internally to retrieve the data. This limits performance and offers potential for improvement. Exasol has a built-in `IMPORT FROM ORA` command to read data from an Oracle database, but this command is not yet used. This command has a performance advantage (implemented in C++ and can load in parallel) over the JDBC driver while providing the same features.

**Proposed improvement**:
To improve on the current performance situation, a new `IMPORT_FROM_ORA` option will be introduced. When activated, the virtual schema will use the `IMPORT FROM ORA` command to fetch data from the Oracle database. The JDBC connection will still be required to fetch meta data (e.g., schemas, table columns, etc.). Additionally an Oracle connection string will be needed which is used in `IMPORT_FROM_ORA`.

This feature is inspired by the already existing `IMPORT_FROM_EXA` property, which allows using the faster `IMPORT FROM EXA` for Exasol data sources.

**Comment by andrehacker** [comment]
This is now merged
