### ISSUE TITLE
Improve Capabilities Documentation

### ISSUE THREAD

**Issue by exanm** [exasol/virtual-schemas#260]
The capabilities documentation https://github.com/exasol/virtual-schemas/blob/master/doc/development/virtual_schema_api.md#get-capabilities just links to the source files. The problem is that the actual capability names are a bit different, e.g. `FN_AGG_COUNT_STAR` instead of `COUNT_STAR`. Also, the list of capabilities is split across multiple files, so adapter developers have to look through all of those. A single list with proper names would be more user friendly.

**Comment by exanm** [comment]
### Capability Prefixes
Main Capabilities: No prefix
Literal Capabilities: `LITERAL_`
Predicate Capabilities: `FN_PRED_`
Scalar Function Capabilities: `FN_`
Aggregate Function Capabilities: `FN_AGG_`

**Comment by AnastasiiaSergienko** [comment]
Closed with #331
