### ISSUE TITLE
Investigate if BINARY type maps without errors 

### ISSUE THREAD

**Issue by AnastasiiaSergienko** [exasol/virtual-schemas#265]
## Problem
The default mapping for Types.BINARY(-2) -> fallBackToMaximumSizeVarChar().

It didn't work with MySQL dialect. The error was thrown from EXALoader:
`[Code: 0, SQL State: 42636]  ETL-5402: JDBC-Client-Error: JDBC SQL Type for column=0 (starting at 0) value=-2 is unknown.`

We need to investigate if BINARY works for other dialects with this default mapping. If it doesn't -> DataType.createUnsupported();

**Comment by redcatbear** [comment]
I found a bug in the handling of the ColumnAdapterNotes. But that was introduced in VSC JDBC after the version that the VS use. So we can rule that out as a cause.

**Comment by AnastasiiaSergienko** [comment]
We decided not to support binary by default. I close this ticket.
