### ISSUE TITLE
Oracle Dialect: Unsupported JDBC data type "-8"

### ISSUE THREAD

**Issue by exaValerieWiedemann** [exasol/virtual-schemas#270]
One of our customers is getting the following error when creating a new virtual schema on Oracle. Other virtual schemas have already successfully been created to that Database, therefore the connection can't be the cause. It seems like an issue with an unknown datatype.

![grafik](https://user-images.githubusercontent.com/35218717/65614494-073e2300-dfb8-11e9-975c-bee0f7a41f93.png)

**Comment by AnastasiiaSergienko** [comment]
The error message tells me that it's an old version of VS. We fixed this bug already.
But I can see that we don't support ROWID column type in Oracle in the latest release. It's just skipped during columns mapping. 
I'm going to add support for ROWID column type.

**Comment by exaValerieWiedemann** [comment]
A colleague had another error with "-3" instead of "-8".
-3 is the VARBINARY type, could you also include that one?

**Comment by AnastasiiaSergienko** [comment]
VARBINARY is officially not supported. VARBINARY columns can only be skipped, it happens automatically in the latest release.

**Comment by alanborgescarvalho** [comment]
Hi Anastasiia, I have attached a csv file which contains the filtered data types which we do not support. I understand some of them will not be possible. Some data types which we support may be on that list, apologies for that.
[incompatible_data_types_found.txt](https://github.com/exasol/virtual-schemas/files/3657718/incompatible_data_types_found.txt)

Here is the complete Excel spreadsheet the prospect sent to me which contains more info.
[data_types.xlsx](https://github.com/exasol/virtual-schemas/files/3657735/data_types.xlsx)

If you need anything or any help, let me know.

**Comment by AnastasiiaSergienko** [comment]
I checked data types from the file. All user defined data types are not supported.
Standard data types from the list:

LONG - supported
CLOB - supported
LONG RAW - won't be supported
NVARCHAR2 - supported
RAW - won't be supported
ROWID - will be supported in the next release
TIMESTAMP - supported

I don't know why supported types are in the list. We need CREATE TABLE statement to investigate the issue. 
Additional information about data types and mapping in Oracle can be found at the end of this file: 
https://github.com/exasol/virtual-schemas/blob/master/doc/dialects/oracle.md
