### ISSUE TITLE
Add supported data types list to Aurora dialect documentation

### ISSUE THREAD

**Issue by AnastasiiaSergienko** [exasol/virtual-schemas#273]
## Problem 
We don't have a list of supported data types for dialects currently.

## Solution
Create a list (or a table) with all data types for each dialect and mark data types as supported/unsupported, add comments about restrictions and mapping when necessary.

- [ ] Aurora

**Comment by jakobbraun** [comment]
oracle was added in #369

**Comment by AnastasiiaSergienko** [comment]
Added SQL Server in #368
