### ISSUE TITLE
SQLSERVER dialect translates CURRENT_DATE incorrectly

### ISSUE THREAD

**Issue by AnastasiiaSergienko** [exasol/virtual-schemas#281]

**Comment by AnastasiiaSergienko** [comment]
I investigated the issue and found out that it's a known bug in SQL SERVER JDBC driver.
See here: https://sourceforge.net/p/jtds/bugs/679/

**Comment by AnastasiiaSergienko** [comment]
I tested with another driver and it worked as expected.
`mssql-jdbc-7.2.2.jre8.jar`
https://www.microsoft.com/en-us/download/details.aspx?id=57782

**Comment by redcatbear** [comment]
Good work. Thanks!
Please add that information to the documentation.

**Comment by AnastasiiaSergienko** [comment]
A new ticket for testing a new driver was created: https://github.com/exasol/virtual-schemas/issues/283

**Comment by AnastasiiaSergienko** [comment]
Added information about driver's bug to the documentation: #284  
This ticket will be closed.
