### ISSUE TITLE
Conflict between FILTERED_TABLES and refresh request

### ISSUE THREAD

**Issue by redcatbear** [exasol/virtual-schemas#290]
## Situation

Users can specify that only selected tables are mapped by the Virtual Schema via the parameter [`FILTERED_TABLES`](https://github.com/exasol/virtual-schemas/blob/master/doc/user-guide/user_guide.md#common-optional-properties).

In the refresh request of the VS API tables can also be selected. Currently the two mechanisms seem to clash in the `BaseMetadataReader`.

## Acceptance Criteria

1. New Unit test proves that table filter via parameter and in refresh request work together.

**Comment by AnastasiiaSergienko** [comment]
This bug affects all dialects (I reproduced it with Exasol dialect). 
It should be fixed in virtual-schema-common-jdbc module. 
Created an issue: https://github.com/exasol/virtual-schema-common-jdbc/issues/13

**Comment by AnastasiiaSergienko** [comment]
Bug is fixed. The next release of this project will provide fixed functionality.
