### ISSUE TITLE
Documentation: Where to find docker port and password for bucketfs upload

### ISSUE THREAD

**Issue by jakobbraun** [exasol/virtual-schemas#311]
[Here](https://github.com/exasol/virtual-schemas/blob/master/doc/user-guide/deploying_the_virtual_schema_adapter.md#uploading-the-adapter-jar-archive) an hint on the different bucketfs-port for docker-db would be nice. Also a hint on how to find out the write password for the docker-db would be very helpful (`awk '/WritePasswd/{ print $3; }' EXAConf | base64 -d`). Maybe it could be added to the [docker_db documentation](https://github.com/exasol/docker-db) and just linked. Right now it already can be found under the [docker_db documentation](https://github.com/exasol/docker-db) but only under the section [Installing Oracle drivers](https://github.com/exasol/docker-db#installing-oracle-drivers)

**Comment by jakobbraun** [comment]
I opened a separate issue for docker-db documentation: https://github.com/exasol/docker-db/issues/46 If it will be realised this section could be linked.

**Comment by AnastasiiaSergienko** [comment]
https://docs.exasol.com/administration/on-premise/manage_network/system_network_settings.htm

**Comment by jakobbraun** [comment]
waiting for https://github.com/exasol/docker-db/pull/52

**Comment by jakobbraun** [comment]
Now docker-db contains the missing information: https://github.com/exasol/docker-db#connecting-to-bucketfs

**Comment by jakobbraun** [comment]
Will not be part of the documentation since docker-db is not officcially supported
