### ISSUE TITLE
'--/' missing in virtual schema documentation

### ISSUE THREAD

**Issue by LennartAtExasol** [exasol/virtual-schemas#379]
https://github.com/exasol/virtual-schemas/blob/master/doc/dialects/sql_server.md

is missing '--/' in front of the script call which causes the script to fail on execution. A non Exasol will not know that this is required, hence it should be added to the documentation.

**Comment by redcatbear** [comment]
We discussed that a couple of times. The problem you describe is specific to one single SQL client.
We have a troubleshooting section that describes how to deal with the script in DBVis.
Adding stuff that is for a single client and does nothing but confuse users of other client is not ideal.

**Comment by redcatbear** [comment]
https://github.com/exasol/virtual-schemas/blob/master/doc/user-guide/sql_clients.md#dbvisualizer
