### ISSUE TITLE
API Documentation: Adapter Notes Must be Strings

### ISSUE THREAD

**Issue by exanm** [exasol/virtual-schemas#384]
The API documentation for the `adapterNotes` field says:

> It can be an arbitrarily nested Json document.

This was never the case. The value for the `adapterNotes` field must be a string.

The examples for `adapterNotes` could be changed to quoted strings.

**Comment by redcatbear** [comment]
@exanm, please review: #385

**Comment by AnastasiiaSergienko** [comment]
Closed with #385
