### ISSUE TITLE
Connecting To a Kerberos Secured Hadoop

### ISSUE THREAD

**Issue by gcekol** [exasol/virtual-schemas#415]
I have Exasol version 7 installed and I'm through DBVisualizer I'm trying to make a virtual shema and connect to Impala.
I've been following this instructions:
https://github.com/exasol/virtual-schemas/blob/master/doc/dialects/impala.md

I have all the data needed:
Kerberos principal for Hadoop (i.e., Hadoop user)
Kerberos configuration file path (e.g., krb5.conf) - stored locally on my laptop
Kerberos keytab file path, which contains keys for the Kerberos principal - stored locally on my laptop
JDBC connection string

This is the syntax I used:

CREATE SCHEMA BD_IMP_ADAPTER;

--/
CREATE OR REPLACE JAVA ADAPTER SCRIPT BD_IMP_ADAPTER.BD_ADAPTER AS
%scriptclass com.exasol.adapter.RequestDispatcher;
%jar /buckets/bfsdefault/jars/virtual-schema-dist-7.0.0-bundle-4.0.4.jar;
%jar /buckets/bfsdefault/jars/ImpalaJDBC41.jar;
/
;

CREATE OR REPLACE CONNECTION IMPALA_CONNECTION TO 'jdbc:impala://:;AuthMech=1;KrbRealm=EXAMPLE.COM;KrbHostFQDN=host.example.com;KrbServiceName=impala'
USER 'user@EXAMPLE.COM' IDENTIFIED BY 'ExaAuthType=Kerberos;long string of letters and numbers';

Is there any difference if I use IP adress instead of server name?

I get an error message while creating virtual shema:
[Code: 0, SQL State: 22002] VM error: F-UDF-CL-LIB-1126: F-UDF-CL-SL-JAVA-1006: F-UDF-CL-SL-JAVA-1026:
com.exasol.ExaUDFException: F-UDF-CL-SL-JAVA-1068: Exception during singleCall adapterCall
com.exasol.adapter.jdbc.RemoteMetadataReaderException: Unable to create Impala remote metadata reader. Caused by: [Cloudera]ImpalaJDBCDriver Error creating login context using ticket cache: Unable to obtain Principal Name for authentication .
com.exasol.adapter.dialects.impala.ImpalaSqlDialect.createRemoteMetadataReader(ImpalaSqlDialect.java:127)
com.exasol.adapter.dialects.AbstractSqlDialect.readSchemaMetadata(AbstractSqlDialect.java:138)
com.exasol.adapter.jdbc.JdbcAdapter.readMetadata(JdbcAdapter.java:56)
com.exasol.adapter.jdbc.JdbcAdapter.createVirtualSchema(JdbcAdapter.java:33)
com.exasol.adapter.RequestDispatcher.dispatchCreateVirtualSchemaRequestToAdapter(RequestDispatcher.java:110)
com.exasol.adapter.RequestDispatcher.processRequest(RequestDispatcher.java:70)
com.exasol.adapter.RequestDispatcher.executeAdapterCall(RequestDispatcher.java:52)
com.exasol.adapter.RequestDispatcher.adapterCall(RequestDispatcher.java:41)
com.exasol.ExaWrapper.runSingleCall(ExaWrapper.java:100)
Caused by: java.sql.SQLException: [Cloudera]ImpalaJDBCDriver Error creating login context using ticket cache: Unable to obtain Principal Name for authentication .

I have read that I need to use the JAAS Java API.
After the JDK installation is there anything else i need to configure?

Thank you in advance!

Goran

**Comment by morazow** [comment]
Hello @gcekol,

Thanks for moving the ticket here. It helps us to collect issues per project.

Please also check the [Hive dialect documentation](https://github.com/exasol/virtual-schemas/blob/master/doc/dialects/hive.md#connecting-to-a-kerberos-secured-hadoop), even though the Impala and Hive are different services, the Kerberos mechanism works same for both.

The issue seems to be related to the Kerberos principal. Could you please add principal to the connection string?

For example,

```
CREATE OR REPLACE CONNECTION IMPALA_CONNECTION TO 'jdbc:impala://:;AuthMech=1;KrbRealm=EXAMPLE.COM;KrbHostFQDN=host.example.com;KrbServiceName=impala;principal=impala/_HOST@EXAMPLE.COM'
USER 'user@EXAMPLE.COM' IDENTIFIED BY 'ExaAuthType=Kerberos;long string of letters and numbers';
```

Additionally, please check if the Kerberos connection uses Thrift or HTTP protocols. If it is HTTP protocol, you should add `transportMode` and `httpPath` properties to connection string.

**Comment by gcekol** [comment]
Hello Muhammet,

I think Kerberos connection uses HTTP protocols.

Here is the full connection syntax.
Could you please check it and let me know how to add the properties you
mentioned above into this connection string?

Thank you!

Goran

**Comment by gcekol** [comment]
Connection string:

*CREATE* *OR* *REPLACE* *CONNECTION* IMPALA_CONNECTION *TO*
'jdbc:impala://bdsimphue.bdsim.sit.pbz.hr:21050;AuthMech=1;KrbRealm=
BDSIM.SIT.PBZ.HR <http://bdsim.sit.pbz.hr/>;KrbHostFQDN=
bdsimphue.bdsim.sit.pbz.hr;

KrbServiceName=impala;principal=impala/_BDSIMPHUE@BDSIM.SIT.PBZ.HR'

*USER* 'bddwh@BDSIM.SIT.PBZ.HR' *IDENTIFIED* *BY*
'ExaAuthType=Kerberos;W2xpYm—';

**Comment by morazow** [comment]
Okay, then please add principal, transportMode and httpPath properties.

An example connection string:

```
CREATE OR REPLACE CONNECTION IMPALA_CONNECTION TO 'jdbc:impala://:;AuthMech=1;KrbRealm=EXAMPLE.COM;KrbHostFQDN=host.example.com;KrbServiceName=impala;transportMode=http;httpPath=cliservice;principal=impala/_HOST@EXAMPLE.COM'
USER 'user@EXAMPLE.COM' IDENTIFIED BY 'ExaAuthType=Kerberos;long string of letters and numbers';
```

Adapting for your connection string it should look as below:

```
CREATE OR REPLACE CONNECTION IMPALA_CONNECTION TO
'jdbc:impala://bdsimphue.bdsim.sit.pbz.hr:21050;AuthMech=1;KrbRealm=BDSIM.SIT.PBZ.HR;KrbHostFQDN=bdsimphue.bdsim.sit.pbz.hr;KrbServiceName=impala;transportMode=http;httpPath=cliservice;principal=impala/_BDSIMPHUE@BDSIM.SIT.PBZ.HR'
USER 'bddwh@BDSIM.SIT.PBZ.HR' 
IDENTIFIED BY 'ExaAuthType=Kerberos;W2xpYm—';
```
You could change principal to `principal=impala/_HOST@BDSIM.SIT.PBZ.HR`, but above should be also fine.

We do not set `KrbAuthType` by default (setting it to 0 is same) at all in the connection string. This way driver will try to automatically obtain the Kerberos subject from JAAS or ticket cache.

**Comment by gcekol** [comment]
Thank you for the detailed answer.

One more thing, regarding JAAS.
I need to install J2SDK and JAAS is implemented in the product. Do I need
to make some kind of changes there or is the installation by itself enough?

**Comment by morazow** [comment]
You do not have to implement anything on your side.

JAAS and Kerberos libraries are already included using the Java `java.security.*` and `javax.security.auth.*` packages in the Virtual Schemas.

**Comment by gcekol** [comment]
But  I do need to install JAAS locally?

**Comment by morazow** [comment]
Hello @gcekol,

I assume when you say locally, you mean your development environment? No, you do not have to install JAAS locally. 

It should be enough if you SQL client to interact with Exasol database.

**Comment by gcekol** [comment]
I am asking because of this:

Connecting To a Kerberos Secured Hadoop

Connecting to a Kerberos secured Impala service only differs in one aspect:
You have a CONNECTION object which contains all the relevant information
for the Kerberos authentication.
<https://github.com/exasol/virtual-schemas/blob/master/doc/dialects/impala.md#understanding-how-it-works-optional>Understanding
how it Works (Optional)

Both the adapter script and the internally used IMPORT FROM JDBC statement
support Kerberos authentication. They detect, that the connection is a
Kerberos connection by a special prefix in the IDENTIFIED BY field. In such
case, the authentication will happen using a Kerberos keytab and Kerberos
config file (*using the JAAS Java API*).

**Comment by morazow** [comment]
Yes, this happens inside the database, that should already have these libraries available.

**Comment by gcekol** [comment]
When I say locally, I mean that I have DbVisualizer installed on my laptop
and through DBVisualizer I'm trying to do all of this.

And I still get the same error message, that's why I thought I maybe need
to do something else locally.

**Comment by morazow** [comment]
Hey @gcekol,

Could you please open remote logging and share the logs (remove confidential parts)?

You can read this [remote logging document](https://github.com/exasol/virtual-schemas/blob/master/doc/development/remote_logging.md) how to do it. Briefly, open a listener, for example, netcat in management server, and set debug and log levels.

**Comment by gcekol** [comment]
I've tried to do it, although I'm doing this from a Windows machine.
I got the IP address. Not sure how to opet a port.

Anyway, the syntax is:

CREATE VIRTUAL SCHEMA BD_VIRTUAL
USING BD_IMP_ADAPTER.BD_ADAPTER
WITH CONNECTION_NAME='IMPALA_CONNECTION'
     SCHEMA_NAME='DWH_TGT' SQL_DIALECT='IMPALA' -- (THIS IS NOT
UPPORTED)IS_LOCAL='true'
     DEBUG_ADDRESS='10.1.45.9:3000' LOG_LEVEL='ALL';

When I ran this, the same error message appeared and I don't know when
to get the log.

**Comment by morazow** [comment]
Hello @gcekol,

You should open a listener (for example netcat, `nc -lkp 3000`) on the `10.1.45.9` address.

Then you can copy the logs from the terminal. 

If logs contain any confidential information, please open a support ticket.

**Comment by gcekol** [comment]
Do you perhaps know how to do it in Windows, since I cannot install netcat
on my laptop, because of company policy?
I'm trying to find an alternative to  netcat, nc -lkp 3000 command

**Comment by redcatbear** [comment]
Hi @gcekol. The team around NMap made a portable variant of netcat for windows: https://nmap.org/ncat/

**Comment by morazow** [comment]
Hey @gcekol,

You could also use [this debugging script](https://raw.githubusercontent.com/exasol/hadoop-etl-udfs/master/tools/udf_debug.py) with Python.

```sh
wget https://raw.githubusercontent.com/exasol/hadoop-etl-udfs/master/tools/udf_debug.py .
python udf_debug.py
```

**Comment by gcekol** [comment]
I've tried to python script.

C:\Users\gcekol\AppData\Local\Programs\Python\Python38-32>udf_debug.py
>>> bind the output server to 192.168.5.21:3000


--/
CREATE VIRTUAL SCHEMA BD_VIRTUAL
    USING BD_IMP_ADAPTER.BD_ADAPTER 
    WITH
    CONNECTION_NAME = 'IMPALA_CONNECTION'
    SCHEMA_NAME     = 'dwh_tgt' SQL_DIALECT = 'IMPALA'
    DEBUG_ADDRESS = '192.168.5.21:3000' LOG_LEVEL='ALL' 
    ;
    
Error is still the same. :(

**Comment by morazow** [comment]
Hey @gcekol,

Could you please share the logs? It would help to better understand at which point the error happens, and give a little context where it occurs.

**Comment by gcekol** [comment]
There are no logs generated.
I don't see it in Command Prompt window...
Is there somekind of log that is generated locally?

**Comment by morazow** [comment]
That is strange.

Could you please [open a support ticket](https://www.exasol.com/support) and arrange a time for a short call next week?

We can check it further during the call.

**Comment by gcekol** [comment]
Unfortunately, I'm doing this on Community version, so a support ticket is not possible.

**Comment by morazow** [comment]
Hello @gcekol,

That is too bad, you should switch to paid version ;) 

Joke aside, please feel free to send an invitation to `opensource at exasol dot com`.

**Comment by gcekol** [comment]
Problem is finally solved! Big thanks got to the whole Exasol team, especially to Muhammet.

Basically, the problem was in communication between Exasol and Big Data servers. Exasol wasn't unable to communicate with those servers and the solution was to set up DNS settings in ExaOperations.
After that everything works as expected.

**Comment by morazow** [comment]
Hey @gcekol,

Thanks for kind words. It was pleasure working with you.

Best
