### ISSUE TITLE
Fix documentation for UDF debugging

### ISSUE THREAD

**Issue by ckunki** [exasol/virtual-schemas#481]
See also https://github.com/exasol/impala-virtual-schema/issues/13 and https://github.com/exasol/hive-virtual-schema/issues/31 

#### Background

Currently docs.exasol.com describes three different approaches for UDF logging.

* [Debug UDF Script Output](https://docs.exasol.com/db/latest/database_concepts/udf_scripts/debug_udf_script_output.htm) mentions a different script [udf_debug.py](https://github.com/EXASOL/hadoop-etl-udfs/blob/master/tools/udf_debug.py) with identical name 
  * repository hadoop-etl-udfs is archived, though.
  * referred script is available only for Python 2.0 and has not been ported to Python 3, yet.
* "[For Python 3.x](https://docs.exasol.com/db/latest/database_concepts/udf_scripts/debug_udf_script_output.htm?Highlight=udf%20script%20output)" mentions [pyexasol debug mode](https://github.com/exasol/pyexasol/blob/master/docs/SCRIPT_OUTPUT.md#debug-mode) which is
  * preferred 
  * but currently limited to a single connection
* [Virtual Schema Logging](https://docs.exasol.com/db/latest/database_concepts/virtual_schema/logging.htm) describes `nc -lkp` which requires neither python nor pyexasol but also some limitations
  * not available on windows or requires installation of additional software  
  * output of potentially multiple clients is merged and cannot be separated

**Comment by ckunki** [comment]
Currently [docs.exasol.com](https://docs.exasol.com/db/latest/database_concepts/udf_scripts/debug_udf_script_output.htm) mentions [UDF Debug Python](https://github.com/EXASOL/hadoop-etl-udfs/blob/master/tools/udf_debug.py).

Repository `hadoop-etl-udfs` is archived, though.

**Comment by allipatev** [comment]
```
Microsoft Windows [Version 10.0.22000.1219]
(c) Microsoft Corporation. All rights reserved.

C:\Users\<my user name>>nc
'nc' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by ckunki** [comment]
On windows one could potentially use https://nmap.org/ncat/

**Comment by ckunki** [comment]
https://github.com/exasol/exasol-python-test-framework/blob/master/exasol_python_test_framework/udf/udf_debug.py
