### ISSUE TITLE
Remove or refactor `com.exasol.utils.SqlTestUtil`

### ISSUE THREAD

**Issue by redcatbear** [exasol/virtual-schemas#72]
# Situation
I stumbled over a static helper class `SqlTestUitl`. Apart from the fact that the name is poorly chosen, the contstructor is not hidden, it is not final and it resides in the `main` source folder instead of `test`.

# Acceptance criteria
1. Find out if this is really test code (quick scan indicates it is)
1. If it is test code, move it to `test`
1. Find out if it needs to be in a static helper class or belongs somewhere else.
1. If it stays in a static helper class:
    * Give that class a proper name (`*util*` is not acceptable)
    * Hide the constructor
    * Make the class static

**Comment by AnastasiiaSergienko** [comment]
Duplicated ticket: #86
