### ISSUE TITLE
Deprecate use of properties CONNECTION_STRING, USERNAME and PASSWORD

### ISSUE THREAD

**Issue by snehlsen** [exasol/virtual-schemas#84]
We will deprecate the use of the properties **CONNECTION_STRING**, **USERNAME** and **PASSWORD**.
### Background
Using these properties the username and password are exposed through the virtual schema requests and responses. It is highly recommended to encapsulate this data in a dedicated connection object.

### Todos
* Remove properties from documentation.
* Add a warning and explanation to documentation.

### Future plans
Throw an error if these properties are used and add the option to ignore this error. This is a breaking change and will be introduced at a later time.

**Comment by AnastasiiaSergienko** [comment]
Done already
